# Site settings
title: Steppor
email: palipalo9@googlemail.com
description: "A Launchpad Step Sequencer for Renoise"
baseurl: "/steppor"
url: "http://mrvandalo.github.io"

# Build settings
markdown: kramdown
permalink: pretty
limit_posts: 5
