# Site settings
title: Steppor
email: palipalo9@googlemail.com
description: "A Launchpad Step Sequencer for Renoise"
baseurl: ""
url: "http://mrvandalo.github.io/steppor/"

# Build settings
markdown: kramdown
permalink: pretty
limit_posts: 5
